### PR TITLE
Improved README and composer

### PR DESCRIPTION
**Pull request by razbakov**

### CODE REVIEW

**Comment by GordonLesti** [comment]
@razbakov I will merge now and tomorrow I will create a PR for https://github.com/magento-hackathon/composer-repository and change the composer.json a little bit?

**Comment by razbakov** [comment]
@GordonLesti do you have idea how to improve it?

**Comment by GordonLesti** [comment]
@razbakov No, but after a PR to https://github.com/magento-hackathon/composer-repository, we can do it without

```
{
    "repositories": [
        {"type": "composer", "url": "http://packages.firegento.com"}
    ]
}
```

in the `README.md` or I'm wrong?

**Comment by razbakov** [comment]
@GordonLesti actually the solution is to add packages.firegento.com to packagist.org,
I already spoke with them:

screen shot 2015-01-13 at 18 15 20

**Comment by GordonLesti** [comment]
Ahh, so I should better add the extension to packagist.org? Would it be better if I remove `gordonlesti/lesti_fpc` from https://github.com/magento-hackathon/composer-repository and add it to packagist? Will http://packages.firegento.com/ be shut down?

**Comment by razbakov** [comment]
> I remove gordonlesti/lesti_fpc from https://github.com/magento-hackathon/composer-repository

gordonlesti/lesti_fpc is not in there in composer-repository
you can see it in README in composer.json
we just add your repo to show composer where to look for your module

```
"repositories": [
        {"type": "git", "url": "https://github.com/GordonLesti/Lesti_Smtp"},
    ],
```

Its possible to remove this line if you add your module to packagist.
But for all magento modules developers use firegento repo.
Of course it would be better to use packagist and not to have additional line in composer.json.
I don't know why it is like that.

> Will http://packages.firegento.com/ be shut down?

As far as it is supported and used by firegento, and they organize a lot of hackatons, i think it will not.

**Comment by GordonLesti** [comment]
I was just confused by `moving packages.firegento.com to packagist.org` and thought packages.firegento.com will be shut down. So I will add `gordonlesti/lesti_smtp` to packages.firegento.com today and merge this PR.

**Comment by razbakov** [comment]
I suggested to add firegento repo to packagist and here is what firegento community thinks about it: https://github.com/magento-hackathon/composer-repository/issues/130

**Comment by GordonLesti** [comment]
@razbakov makes sence, sorry that already have added the extension to magento-hackathon/composer-repository, but I will after my exams

**Pull request merged**
